"""Ptables v1

Revision ID: 2a4027247fb8
Revises: 74558415c129
Create Date: 2022-11-28 13:56:52.704055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4027247fb8'
down_revision = '74558415c129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ptable',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('aside', sa.String(length=32), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('pcolumn',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('sortingType', sa.Text(), nullable=True),
    sa.Column('ptable_uuid', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['ptable_uuid'], ['ptable.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pcolumn')
    op.drop_table('ptable')
    # ### end Alembic commands ###
