"""empty message

Revision ID: 74558415c129
Revises: 
Create Date: 2022-11-14 15:55:08.180275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74558415c129'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_field')
    with op.batch_alter_table('formField', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formField', schema=None) as batch_op:
        batch_op.drop_column('description')

    op.create_table('form_field',
    sa.Column('uuid', sa.VARCHAR(length=32), nullable=False),
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('label', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('min', sa.TEXT(), nullable=True),
    sa.Column('max', sa.TEXT(), nullable=True),
    sa.Column('formtask_uuid', sa.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['formtask_uuid'], ['formTask.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###
